nl = chr(10)
code = [
    'from mcp.server.fastmcp import FastMCP',
    'import httpx',
    'import logging',
    '',
    'logging.basicConfig(level=logging.DEBUG)',
    'logger = logging.getLogger(__name__)',
    '',
    'API_URL = "http://127.0.0.1:3006"',
    'PORT = 3008',
    'API_KEY = "fc-selfhosted"',
    '',
    'mcp = FastMCP("firecrawl-python")',
    '',
    '@mcp.tool()',
    'async def firecrawl_search(query: str, limit: int = 5) -> str:',
    '    logger.info(f"Searching: {query}")',
    '    async with httpx.AsyncClient(timeout=60.0) as client:',
    '        try:',
    '            response = await client.post(',
    '                f"{API_URL}/v1/search",',
    '                headers={"Content-Type": "application/json", "Authorization": f"Bearer {API_KEY}"},',
    '                json={"query": query, "limit": limit, "scrapeOptions": {"formats": ["markdown"]}}',
    '            )',
    '            data = response.json()',
    '            if not data.get("success"): return f"Error: {data.get("error")}"',
    '            results = data.get("data", [])',
    '            output = []',
    '            for i, item in enumerate(results):',
    '                title = item.get("title", "No Title")',
    '                url = item.get("url", "#")',
    '                entry = f"Result {i+1}: {title} ({url})"',
    '                output.append(entry)',
    '            return nl.join(output)',
    '        except Exception as e:',
    '            return f"Exception: {str(e)}"',
    '',
    'if __name__ == "__main__":',
    '    mcp.settings.port = PORT',
    '    mcp.settings.host = "0.0.0.0"',
    '    mcp.run(transport="sse")'
]

with open('/home/mike/firecrawl-custom-mcp/server.py', 'w') as f:
    f.write(nl.join(code))
